apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: ulys
  annotations:
    iam.gke.io/gcp-service-account: ${API_GSA_EMAIL}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: ulys
  annotations:
    iam.gke.io/gcp-service-account: ${WORKER_GSA_EMAIL}
